[workspace]
members = [
    "savant-zulrah",
    "savant-parser",
]
resolver = "2"

[profile.release]
debug = false
incremental = true
codegen-units = 256

[profile.dev.package.randomize]
opt-level = 3
